import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BanChecker from "@/components/BanChecker";
import CollapsibleNavBar from "@/components/navigationBar";
import { ThemeProvider } from "@/context/ThemeContext";
import ErrorBoundary from "@/components/ErrorBoundary";
import NotificationInitializer from "@/components/NotificationInitializer";

// Import React for useEffect
import { useEffect } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Note: The NotificationInitializer component will handle the notification permissions
  // since we can't use useEffect directly in this server component

  return (
    <html lang="en">
      <head>
        <link
          rel="manifest"
          href="/manifest.json"
          crossOrigin="use-credentials"
        />
        <link rel="apple-touch-icon" href="/icon.png"></link>
        <meta name="theme-color" content="#fff" />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BanChecker />
        <ThemeProvider>
          {/* <Navbar /> */}
          {/* Add NotificationInitializer as a client component */}
          <NotificationInitializer />
          <main className="pt-0">
            {/* pt-16 adds padding-top that matches navbar height */}
            {children}
          </main>
          <CollapsibleNavBar />
        </ThemeProvider>
      </body>
    </html>
  );
}
